# CM Stack Configuration
# ===================

# Domain Configuration
base_domain: "your-subdomain.example.com"  # Base domain for all services

# TLS Configuration
tls:
  enabled: true                       # Will automatically deploy cert-manager if true
  email: "your-email@example.com"     # Email for Let's Encrypt notifications
  # If you have your own certificate, provide files in .secrets/tls/:
  # - fullchain.pem (certificate including intermediate and root certificates)
  # - privkey.pem (private key)
  use_own_cert: false                 # Use your own certificate instead of Let's Encrypt

# Storage Configuration
storage:
  deploy_longhorn: false              # Deploy Longhorn CSI storage
  snapshot_class: "longhorn"         # VolumeSnapshot class name for backup operations
                                    # Examples: longhorn, csi-hostpath-snapclass

# Database Backup Configuration
database_backup:
  enabled: true                      # Enable database backups
  retention_days: 3                  # How many days to keep backups
  schedule: "0 0 */4 * * *"         # Backup schedule (cron format)

# GPU Support
gpu: none                           # Possible values: nvidia, none (amd support coming soon)

# The following components and files are required:
# - Prometheus monitoring stack (always deployed)
# - Container registry credentials (read from .secrets/cm-images.json)
# - SSH keys for repositories (read from .secrets/cm-stack-*)