# CM Stack Configuration
# ===================

# Domain Configuration
base_domain: "<cm-stack-subdomain.example.com>"  # Base domain for all services

# TLS Configuration
tls:
  enabled: true                       # Will automatically deploy cert-manager if true
  email: "<your-email@example.com>"   # Email for Let's Encrypt notifications
  
  use_own_cert: false                 # Use your own certificate instead of Let's Encrypt
                                      # If you have your own certificate, place the files in .secrets/tls/:
                                      # - fullchain.pem (certificate including intermediate and root certificates)
                                      # - privkey.pem (private key)

# Storage Configuration
storage:
  deploy_longhorn: false              # Deploy Longhorn CSI storage.
                                      # *Required* for K3s-like clusters.
                                      # *Optional* for most managed K8s clusters.
                                      # IMPORTANT: Longhorn CSI prerequisites on the host OS level:
                                      # Debian: `apt install open-iscsi nfs-common cryptsetup`
                                      # RedHat: `dnf install iscsi-initiator-utils nfs-utils cryptsetup`
  
  snapshot_class: "<your-snap-class>" # VolumeSnapshot class name for backup operations
                                      # Possible values: longhorn, <your-csi-snapshot-class>

# Database Backup Configuration
database_backup:
  enabled: true                       # Enable database backups
                                      # IMPORTANT: Backup operations requires a valid snapshot class to be set
                                      # in the Storage Configuration section.
  
  retention_days: 3                   # How many days to keep backups
  schedule: "<6-digit-cron-schedule>" # Backup schedule (6-digit cron format [with seconds])
                                      # Example: "0 0 */4 * * *" = every 4 hours

# GPU Support
gpu: none                             # Possible values: nvidia, none (AMD support coming soon)
                                      # Nvidia GPU support requires the following to be installed on the host OS:
                                      # - NVIDIA GPU Drivers 
                                      # - NVIDIA Container Toolkit .
                                      # Use Nvidia GPU operator to install automatically or follow the manual installation guide
                                      # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

# The following components and files are required:
# - Kubeconfig monitoring stack (read from .secrets/kube.conf)
# - Container registry credentials (read from .secrets/cm-images.json)
# - SSH keys for repositories (read from .secrets/cm-stack-*)